alkaline-ml/pmdarima

- .travis.yml
- setup.py
This PR adds continuous deployment to Pypi on tagged commits.
- It will be important to tag commits before pushing so that Travis will build the wheels properly. I believe there is a means to tag it through github itself, which I am fairly certain will not trigger the build of the wheels.
- The wheels that are built do not have OS, architecture, and OS version tied to them. Essentially two wheels are built - one for python 2 and one for python 3. 
@tgsmith61591 Thoughts?
> Add Continuous Deployment to .travis.yml

- MANIFEST.in
- pyramid/__init__.py
- setup.py
See #13. `requirements.txt` was not in the `MANIFEST.in`, and pip could not build from source. Now it can.
> [HOTFIX] 0.5.1

- .travis.yml
- build_tools/travis/build_wheels.sh
I'm unable to install Pyramid from a Wheel on an Amazon Linux EC2 machine. Based on [PEP 513](https://www.python.org/dev/peps/pep-0513/#ucs-2-vs-ucs-4-builds), a `--enable-unicode` flag needs to be passed when building CPython 2.x. (See: https://github.com/tgsmith61591/pyramid/issues/16).
The fix is to add another build to the Travis matrix to build with cp27mu. I refactored the Linux portion of the `build_wheels.sh` to expose the UCS setting and avoid hardcoding it. The rest of the builds will default to UCS-2 (which was the default previously, too) and UCS-4 will only be built when explicitly set in a particular job's env. In short, this simply adds a new build without affecting existing builds.
> Add Linux wheel build with UCS-4 encoding for CPython 2.7

- build_tools/circle/build_push_doc.sh
- doc/whats_new.rst
- pmdarima/arima/_arima.pyx
- pmdarima/arima/approx.py
- pmdarima/arima/stationarity.py
This solves #62 
* Latest release doc will be deployed to `alkaline-ml.com/pmdarima/`
* Latest release doc will be deployed to `alkaline-ml.com/pmdarima/<version>/`
* We build documentation also for `develop` located at `alkaline-ml.com/pmdarima/develop/`
I also manually added versioned doc for [v0.9.0](http://www.alkaline-ml.com/pmdarima/0.9.0/) and [v1.0.0](http://www.alkaline-ml.com/pmdarima/1.0.0/). Eventually we can link to older versions from the home page.
I'm particularly interested in a review of `build_tools/circle/build_push_doc.sh`
I also merged another branch (`improve-cython-speed`) into this branch at one point for some ancillary, related reason, so that branch is also getting merged...
> [MRG] Versioned documentation

- pmdarima/arima/stationarity.py
- pmdarima/arima/tests/test_approx.py
- pmdarima/arima/tests/test_stationarity.py
- pmdarima/arima/utils.py
Issue #67 asked for clarification around the use of the stationarity tests in `pmdarima`. In the process of putting together an example, I found a slight bug in the way we compute `OLS` regression for the augmented Dickey-Fuller test, as well as several other opportunities for improvement. This PR achieves the following:
* Change the `OLS` fit method to use `'qr'` rather than `'pinv'`
* Use the `OLS` result wrapper `bse` attribute to access coefficient standard errors rather than the `H0_se` attribute
* Improve readability in the `KPSS` test
* Include links to R source code in the stationarity test docstrings
* Add several tests and more coverage
> [MRG] Greater stationarity test precision

- .travis.yml
- build_tools/travis/after_wheel_build.sh
- build_tools/travis/build_manywheels_linux.sh
This PR removes the explicit version for `cython`, which was preventing build artifacts for Python 3.7 (#76), and adds a check to make sure our build artifacts were created before deployment.
I added the check in the `before_deploy` section of the build as noted [here](https://docs.travis-ci.com/user/job-lifecycle/#deploying-your-code), so it will only get run on a tagged release (i.e., it won't run when we merge this in). I initially had it in the `after_success` phase, and I am more than happy to move it back, but it made more sense to me here.
> [MRG+1] Py37 build artifacts

- .codecov.yml
- doc/tips_and_tricks.rst
Codecov fails out CI tests for virtually any decrement. This adds `.codecov.yml`, which sets the threshold allowance to 1%.
> [MRG] Improve codecov tolerance

- doc/tips_and_tricks.rst
- doc/whats_new.rst
- pmdarima/arima/stationarity.py
- pmdarima/arima/tests/test_stationarity.py
- pmdarima/arima/utils.py
The tests of stationarity test currently use a function "`is_stationary`" to indicate whether we should difference the time series. However, the nomenclature is backwards. Since we've recently had an issue where someone requested clarification on the test (#67), it makes sense we should change this so it makes more intuitive sense.
* Create new function, "`should_diff`", that replaces `is_stationary`
* If user calls `is_stationary`, raise a `DeprecationWarning` and internally delegate to `should_diff`
We'll remove the `is_stationary` function in 1.4.
> [MRG+1] Deprecate 'is_stationary'

- appveyor.yml
- build_tools/circle/build_test_pypy.sh
Our Appveyor builds are prohibitively slow. We still need all jobs to run since for deployments the wheel has to be built on the appropriate architecture... but we don't always have to run tests.
This PR removes half of the test jobs, just letting the wheels build. It also adds in some more pip caching, although I'm wary as to whether it's actually working properly or not.
Fix more pypy breakage on Circle. Any subsequent PR will have to rebase off these changes once they make it into `develop`
> Less appveyor

- appveyor.yml
This PR addresses #98
We can see the cache is [being used](https://ci.appveyor.com/project/tgsmith61591/pmdarima/builds/22262043/job/qnv2fie979qkav4t#L32) and [being updated](https://ci.appveyor.com/project/tgsmith61591/pmdarima/builds/22262043/job/qnv2fie979qkav4t#L695). I don't know how much time is really being saved (my builds were still taking ~12 minutes). The only additional change we might want to add is to [skip updating cache unless we are on a specific branch](https://www.appveyor.com/docs/build-cache/#skipping-cache-operations-for-specific-build), but I was watching these build in real time, and that step only took like 1 second each.
> [MRG+1] Appveyor cache

- doc/whats_new.rst
- pmdarima/arima/arima.py
- pmdarima/arima/tests/test_arima.py
#111 asked how to access OOB predictions when ``out_of_sample_size > 0``. This PR stores the attribute.
> [MRG+1] Store OOB preds

- azure-pipelines.yml
After doing [a little research](https://stackoverflow.com/a/27154277), and [reading the docs a little bit more](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables), I found that `Build.SourceBranch` would resolve to `refs/tags/<tag>`, and `Build.SourceBranchName` would just resolve to `<tag>`, so the deploy step would fail. I removed the condition that the tag must be on `master`, because as my first link shows, tags and branches are entirely independent.
> [MRG+1] Fix deploy logic on Azure Pipelines

- .circleci/config.yml
- build_tools/circle/before_install.sh
- build_tools/circle/build_test_pypy.sh
Adds one of our `pmdarima-docker` bases as the Pypy circle job base. Speeds up build/runtime from ~30 mins to 3-4 mins.
- CI/CD tests pass, and faster than ever 🤓
> [MRG] New pypy base for Circle job

- pmdarima/arima/arima.py
Change the default `typ` in `predict_in_sample` to be "levels", which is more intuitive. See #166 for more context... this will produce in-sample predictions in the original endogenous scale as opposed to centered around 0.
> [MRG+1] Change default to predict_in_sample to typ=levels

- .codecov.yml
- AUTHORS.md
- Makefile
- doc/index.rst
- doc/whats_new.rst
- examples/example_pipeline.py
- examples/example_simple_fit.py
- pmdarima/__init__.py
- pmdarima/arima/_auto_solvers.py
- pmdarima/arima/_context.py
- pmdarima/arima/_doc.py
- pmdarima/arima/arima.py
- pmdarima/arima/auto.py
- pmdarima/arima/seasonality.py
- pmdarima/arima/tests/test_arima.py
- pmdarima/arima/tests/test_context.py
- pmdarima/compat/statsmodels.py
- pmdarima/utils/wrapped.py
This fixes #211 by updating our `ARIMA` class to only use the statsmodels SARIMAX under the hood, per the thread here: https://github.com/statsmodels/statsmodels/issues/6225#issuecomment-550350284
It should not cause any breaking changes, though it will yield very slightly different results for some parameter combinations. It also will yield two new warnings for explicitly setting the old default values to some hyper-parameters.
All existing tests pass (with minor updates where required), and parity with R package functionality is the same as before.
> [MRG+1] SARIMAX only

- doc/modules/classes.rst
- doc/whats_new.rst
- pmdarima/arima/arima.py
- pmdarima/arima/auto.py
- pmdarima/pipeline.py
- pmdarima/preprocessing/base.py
- pmdarima/preprocessing/exog/base.py
- pmdarima/preprocessing/exog/fourier.py
- pmdarima/preprocessing/exog/tests/test_fourier.py
- pmdarima/tests/test_pipeline.py
- pmdarima/utils/array.py
- pmdarima/utils/tests/test_array.py
Fixes #222. Adds an optional parameter, `prefix`, to exogenous featurizers and pass-through support for pandas DataFrames as exog arrays (rather than converting to np.ndarray). This accomplishes two things:
* If a pandas frame is provided as an exog array to the statsmodels SARIMAX class, it will keep the names intact and the `summary` method will contain the meaningful names
* Featurizer classes will name their generated features with the `prefix`, meaning the summary will contain their variable names as well.
The only case where no meaningful names will be retained is when a numpy array is fed into a featurizer (cannot concatenate numpy and pandas) or directly into a model. Here's an example:
```python
In [1]: from pmdarima.pipeline import Pipeline
...: from pmdarima.preprocessing …
```
> [MRG+1] Add support for meaningful exog names 

- pmdarima/preprocessing/exog/base.py
- pmdarima/preprocessing/exog/fourier.py
One more minor tweak to align more with request in #222 
Amends Fourier feat names to be:
```
FOURIER_S12-0     FOURIER_C12-0    ...     FOURIER_S12-3  FOURIER_C12-3
0       0.500000      8.660254e-01    ...      8.660254e-01           -0.5
1       0.866025      5.000000e-01    ...     -8.660255e-01           -0.5
2       1.000000     -4.371139e-08    ...      1.748456e-07            1.0
3       0.866025     -5.000001e-01    ...      8.660253e-01           -0.5
4       0.500000     -8.660254e-01    ...     -8.660255e-01           -0.5
```
> [MRG+1] Tweak to align a bit more with #222

- doc/whats_new.rst
- pmdarima/arima/_auto_solvers.py
- pmdarima/arima/_doc.py
- pmdarima/arima/arima.py
- pmdarima/arima/auto.py
- pmdarima/preprocessing/exog/tests/test_fourier.py
Since the move to SARIMAX only, we have some deprecated constructor args we can back out. For now, there are warnings if they're found in kwargs. After a few versions we can completely remove the checks
All existing tests pass.
> [MRG+1] Back out deprecated constructor args

- .codecov.yml
- doc/whats_new.rst
- examples/example_pipeline.py
- pmdarima/arima/_auto_solvers.py
- pmdarima/arima/_doc.py
- pmdarima/arima/arima.py
- pmdarima/arima/auto.py
- pmdarima/arima/tests/test_arima.py
- pmdarima/arima/tests/test_auto.py
- pmdarima/model_selection/tests/test_validation.py
- pmdarima/pipeline.py
- pmdarima/preprocessing/endog/__init__.py
- pmdarima/preprocessing/endog/tests/test_base.py
- pmdarima/preprocessing/endog/tests/test_boxcox.py
- pmdarima/preprocessing/exog/__init__.py
- pmdarima/preprocessing/exog/base.py
- pmdarima/preprocessing/exog/tests/test_base.py
- pmdarima/preprocessing/exog/tests/test_fourier.py
- pmdarima/preprocessing/tests/test_base.py
- pmdarima/tests/test_pipeline.py
This is related to #231 and backs out some more deprecated args. It does not break any backwards compatibility, instead just being noisy with `DeprecationWarning`s for now.
> [MRG+1] Deprecate more args

- doc/whats_new.rst
`diffinv` and `diff_inv` were incorrectly labeled as `diffenv` and `diff_env` in the docs from #236 
N/A
> [MRG + 1] Fix doc typo

- doc/modules/classes.rst
- pmdarima/__init__.py
- pmdarima/arima/__init__.py
- pmdarima/arima/seasonality.py
- pmdarima/arima/tests/test_approx.py
- pmdarima/arima/tests/test_arima_diagnostics.py
- pmdarima/arima/tests/test_c_arima.py
- pmdarima/arima/tests/test_seasonality.py
- pmdarima/arima/tests/test_stationarity.py
- pmdarima/datasets/tests/__init__.py
- pmdarima/setup.py
General clean up including, but not limited to:
* Adding link in API ref for `pm.decompose`
* Add `decompose` to top-level API so you can just do `pm.decompose`
* Clean out some old, pre-Python3 imports
* Add an `__init__.py` to `model_selection/tests` which *may* have contributed to breaking build-from-source builds
> [MRG+1] General cleanup

- .circleci/config.yml
- build_tools/circle/build_manylinux_wheel.sh
- build_tools/circle/build_push_doc.sh
- build_tools/circle/build_wheel.sh
- build_tools/circle/test_version_tagging.sh
- build_tools/get_tag.py
- setup.py
The migration to versioning with tags caused a couple problems:
* Even though `sdist` bundled the `VERSION` file, the binary wheels left it out of their MANIFEST.
* `GIT_TAG` may have been deprecated from Circle. We should be using `CIRCLE_TAG`
* There was an order-of-operations error in the doc deployment RE: versioning
* The wheel repair script ignored the version file and would have deployed 0.0.0 versioned binaries, had we not already failed for other reasons.
> [HOTFIX] Hotfix tagged linux deployments

- pmdarima/arima/arima.py
- pmdarima/compat/__init__.py
- pmdarima/compat/sklearn.py
- pmdarima/model_selection/_validation.py
- pmdarima/pipeline.py
- pmdarima/preprocessing/endog/boxcox.py
- pmdarima/preprocessing/exog/fourier.py
Addresses the follow deprecation warnings from [issue#252](https://github.com/alkaline-ml/pmdarima/issues/252):
`0.23`
- `/Users/runner/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/sklearn/utils/validation.py:933: FutureWarning: Passing attributes to check_is_fitted is deprecated and will be removed in 0.23.`
`0.24`
- `FutureWarning: The sklearn.metrics.regression module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.`
> [MRG+2] Sklearn deprecation fixes

- doc/contributing.rst
- doc/index.rst
- doc/whats_new.rst
- examples/example_simple_fit.py
- pmdarima/__init__.py
- pmdarima/utils/_show_versions.py
- pmdarima/utils/tests/test_show_versions.py
This adapts scikit-learn's `show_versions` for our use so that issue-filers can more easily run, e.g.,:
```
>>> import pmdarima as pm
>>> pm.show_versions()
System:
python: 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
executable: /anaconda3/envs/pmdenv/bin/python
machine: Darwin-18.6.0-x86_64-i386-64bit
Python dependencies:
pip: 10.0.1
setuptools: 40.5.0
sklearn: 0.21.3
statsmodels: 0.10.0
numpy: 1.17.3
scipy: 1.3.1
Cython: 0.29
pandas: 0.25.2
joblib: 0.13.2
pmdarima: 1.5.1
```
> [MRG+1] Show versions

- Makefile
- doc/usecases/sun-spots.rst
- doc/whats_new.rst
- pmdarima/arima/_context.py
- pmdarima/arima/_doc.py
- pmdarima/arima/auto.py
- pmdarima/arima/tests/test_arima.py
Fixes #272. Hyndman does not use `start_p`, `start_q`, etc., when `stepwise=False`. This aligns `auto_arima` to be in parity, and removes the `ValueError` when an order exceeds `max_order`, simply omitting that fit.
Removes two tests that are now irrelevant, and all remaining tests pass.
> [MRG+1] Fix max_order bug

- doc/index.rst
This changes a minor typo where we say the bleeding edge docs are built off of the `develop` branch. They are built on the `master` branch currently.
> [MRG+1] change develop to master for note about bleeding edge docs

- doc/whats_new.rst
- pmdarima/arima/_context.py
- pmdarima/arima/tests/test_context.py
- pmdarima/utils/visualization.py
#271 identified an `AttributeError` that can pop up in the stepwise context that seems related to the use of `threading.local` to store the context. This backs out the use of `threading.local` in favor of a global singleton that stores context.
I added a new test that spawns several threads and asserts data is accessible across them.
> [MRG+2] Back out threading.local in favor of global stepwise context

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/QUESTION.md
- pmdarima/utils/_show_versions.py
With the release of 1.5.2 containing `pmdarima.show_versions()`, I updated the issue templates to contain that snippet.
Additionally, I changed the output of `pmdarima.show_versions()` to have width 11 instead of 10. Otherwise, statsmodels sticks out.
```
System:
python: 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52)  [Clang 6.0 (clang-600.0.57)]
executable: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
machine: Darwin-19.0.0-x86_64-i386-64bit
Python dependencies:
pip: 19.3.1
setuptools: 40.8.0
sklearn: 0.22
statsmodels: 0.10.2
numpy: 1.17.4
scipy: 1.3.3
Cython: 0.29.13
pandas: 0.23.4
joblib: 0.14.1
pmdarima: 1.5.2
```
```
System:
python: 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52)  [Clang 6.0 (clang-600.0.57)]
executable: …
```
> [MRG+1] Update issue templates

- .circleci/config.yml
This PR is related to #269 and alkaline-ml/pmdarima-docker#3 -- its purpose is to point to our new pypy docker image instead of the `tgsmith61591` namespace
> [MRG+1] Use new pypy image

- .github/workflows/build_pypy_dependencies.yml
When we merge into master, it creates a new push commit to master. If we updated `requirements.txt`, it will trigger the pypy deps workflow. Since this should_have already run _before_ the PR, we want to avoid this.
Also, I am aware the spacing looks a little funny (indentation on the `branches-ignore` key, but not the `paths` key). I just copied the syntax from the [docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags) for safety
N/A
> [MRG+1] Don't rebuild pypy deps on master

- .github/workflows/badges.yml
- .github/workflows/build_and_deploy.yml
- README.md
- build_tools/azure/conda/deploy.yml
- build_tools/circle/build_push_doc.sh
- build_tools/circle/deploy.sh
This change allows us to test our deployment logic by tagging with _almost any_ tag that (contains a letter)  Examples:
- `v1.5.3rc`
- `v1.5.3rc1`
- `v1.5.3test`
If we tag in this way, the CI/CD pipelines will deploy to:
- test.pypi.org (for PyPI releases)
- Our anaconda.org channel with a label of `test` 
- Adding this label means no one will see it unless they are specifically searching for it ([source](https://docs.anaconda.com/anaconda-cloud/user-guide/tasks/work-with-packages/#uploading-packages))
It also checks to make sure if the version doesn't match the test format, that it matches one of the following before deploying to production:
- `X.Y.Z`
- `X.Y`
I also removed the `fail-fast = False` logic from GitHub Actions, as that is mostly for debugging.
> [MRG+2] Test deployments

- etc/downloads_badges.py
This PR fixes a bug where we had `1,958,958` downloads, which _should_display as `2M` on the badge. However, without the `round(x, 0)` in there, it was truncating `1.958958M` to `1M`
```
millify(1958958)
Out[5]: '2M'
millify(958958)
Out[6]: '959k'
millify(1948958)
Out[7]: '1.9M'
millify(2158958)
Out[8]: '2.2M'
```
> [MRG+1] Fix "Downloads" Badge

- .circleci/config.yml
- build_tools/circle/deploy_doc.sh
This fixes a bug introduced in #287 
According to the [docs](https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs), when we are re-attaching our workspace, we only need to supply the root. Or else it adds extra layers (which is why our docs ended up at alkaline-ml.com/pmdarima/develop/_build/html)
Debugged using `ls`. I `ls`d the `html` directory after renaming and it seems to work.
See [this run](https://app.circleci.com/jobs/github/alkaline-ml/pmdarima/9747/parallel-runs/0/steps/0-103). First `ls` shows the `doc` directory, then the contents of it. The 3rd `ls` shows it has been renamed to `html`, then the contents of it.
> [MRG+1] Fix deploy doc

- build_tools/build_requirements.txt
- build_tools/doc/doc_requirements.txt
- requirements.txt
[Statsmodels release `0.11.0` this morning](https://pypi.org/project/statsmodels/0.11.0/#description), which appears to be incompatible with our code. For the short term, we are pinning to `0.10.*`
[CI/CD is passing](https://app.circleci.com/jobs/github/alkaline-ml/pmdarima/9782), when it [wasn't before](https://app.circleci.com/github/alkaline-ml/pmdarima/pipelines/a7dbe670-dc3e-4a03-80a3-c3ac6174d30a/workflows/54d18f82-d410-4de5-8f8c-4771f8fb46f5)
> [MRG+1] Pin statsmodels to 0.10.*

- .github/workflows/build_and_deploy.yml
- build_tools/azure/conda/deploy.sh
- build_tools/azure/conda/deploy.yml
- build_tools/azure/conda/windows.yml
- build_tools/azure/test_version_tagging.sh
- build_tools/circle/build_wheel.sh
- build_tools/circle/deploy.sh
- build_tools/github/deploy.sh
This PR is necessary to address the 4 issues we saw during the v1.5.3 deploy today.
1. Azure Pipelines found a malformed tag when trying to deploy to Conda (only for Mac and Linux)
* The regex was lazily looking for the last digit: `^[0-9]+\.[0-9]+\.?[0-9]*?$`, so it stopped matching after `1.5.`, leading to a malformed tag. Removing the trailing question mark fixes this. Example:
```bash
set -e
pip install pathlib
BUILD_SOURCEBRANCH=refs/tags/v0.99.999 python ~/Documents/projects/alkaline-ml/pmdarima//build_tools/get_tag.py
if [[ $(cat ~/Documents/projects/alkaline-ml/pmdarima/pmdarima/VERSION) =~ ^[0-9]+\.[0-9]+\.?[0-9]*[a-zA-Z]+[0-9]*$ ]]; then
echo 'Uploading to conda with test label'
elif [[ $(cat ~/Documents/projects/alkaline-ml/pmdarima/pmdarima/VERSION) =~ …
```
> [MRG+1] Hotfix for 1.5.3 deploy

- .github/workflows/build_and_deploy.yml
- build_tools/azure/conda/deploy.yml
On our second attempt to deploy 1.5.3, we ran into 2 issues:
1. [`deploy.sh` could not be found be deploy step](https://dev.azure.com/tgsmith61591gh/pmdarima/_build/results?buildId=1649&view=logs&j=094df02d-42f3-5942-83e9-798405c0fd82&t=54a57d57-cd0f-58ed-98ae-8d9fbd8e293d). This is fixed by giving it the full path to the script
2. [The deploy step on GitHub was never even entered](https://github.com/alkaline-ml/pmdarima/runs/446054604?check_suite_focus=true). The check for `steps.version_check.version_exists` needs to be `steps.version_check.outputs.version_exists`
Working here (with a value of `false`):
Unable to test the other change until deploy time. However, it is the same syntax as [`azure-pipelines.yml`](https://github.com/alkaline-ml/pmdarima/blob/db4a587195b4739c1d5cd7def0ca98c61 …
> [MRG+1] Hotfix take 2

- pmdarima/arima/auto.py
- pmdarima/arima/tests/test_arima.py
When a user specifies information_criterion='oob' but doesn't specify out_of_sample_size while calling auto_arima, no warning is raised. 
Fixes #305 
Raises a warning informing the user about conflicting parameters. Also, switches to default information_criterion='aic'
```
import numpy as np
import pmdarima as pm
from pmdarima.datasets import load_wineind
wineind = load_wineind().astype(np.float64)
stepwise_fit = pm.auto_arima(wineind, start_p=1, start_q=1,
max_p=3, max_q=3, m=12,
start_P=0, seasonal=True,
d=1, D=1, trace=True,
error_action='ignore',  # don't want to know if an order does not work
suppress_warnings=True,  # don't want convergence warnings
stepwise=True, # set to stepwise
information_criterion='oob')  
```
```
auto.py:356: …
```
> [MRG+2] Added check for out_of_sample_size when information_criterion='oob'

- pmdarima/arima/arima.py
- pmdarima/compat/matplotlib.py
In response to issue #308.
The "normed" keyword used in method pmdarima.arima.ARIMA.plot_diagnostics (in reference to matplotlib.pyplot.hist) is deprecated.
It has been removed from matplolib since version 3.2.0, and prevented the plot_diagnostics method from working.
It has been replaced with the new supported keyword argument "density".
> [MRG+2] Replaced keyword argument "normed" to "density" in method pmdarima.arima.ARIMA.plot_diagnostics

- .codecov.yml
- doc/whats_new.rst
- pmdarima/arima/_auto_solvers.py
- pmdarima/arima/auto.py
- pmdarima/arima/tests/test_arima.py
Adds a new `error_action` level, "trace". This behaves like "warn" but dumps the stacktrace as well instead of the generic `may not be stationary` message
> [MRG+1] New error action

- .gitignore
- pmdarima/arima/seasonality.py
- pmdarima/arima/tests/test_seasonality.py
Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context. List any dependencies
that are required for this change.
Fixes #316 
**Input/Code**
```R
require(graphics)
x <- c(1, 2, 3, 4, 5, 6)
x <- ts(x, frequency = 3)
m <- decompose(x)
m
```
**Output**
```R
> # NOT RUN {
> require(graphics)
> 
> ## example taken from Kendall/Stuart
> x <- c(1, 2, 3, 4, 5, 6)
> x <- ts(x, frequency = 3)
> m <- decompose(x)
> m
$x
Time Series:
Start = c(1, 1) 
End = c(2, 3) 
Frequency = 3 
[1] 1 2 3 4 5 6
$seasonal
Time Series:
Start = …
```
> [MRG+2] Fix for issue#316 decompose error where m is odd

- etc/downloads_badges.py
The website we depend on for our downloads badge did not update and we got an [error](https://github.com/alkaline-ml/pmdarima/actions/runs/76033812) due to trying to access a key that did not exist. This PR implements `dict.get(key, default)` instead of `dict[key]` by calculating the default as the average of the last week before summing the values
> [MRG+1] Avoid KeyError on downloads badge script

- doc/whats_new.rst
- pmdarima/arima/arima.py
- pmdarima/arima/tests/test_arima.py
This fixes #286 by adding a ValueError in `predict_in_sample` when `start < d`, a condition for which in-sample predictions are undefined. I originally considered a warning, but in this case, where we're liable to have users ignore a warning and ask why they get junky predictions for the early portion of their series, I do think an error will be best.
Added a new test that reproduces and catches the error to assert it is raised as expected.
> [MRG+1] ValueError for predict_in_sample when start < d

- build_tools/build_requirements.txt
- requirements.txt
The latest Cython was released last night and conflicts with the latest Numpy version. Since we use `numpy.distutils` to build, our nightly jobs are failing. We originally pinned `Cython>=0.29`, but this PR adds a ceiling of `<0.29.18` to avoid build failures until Numpy is compatible with the latest Cython.
> MAINT: Set a ceiling on cython version

- build_tools/doc/doc_requirements.txt
We bumped our Cython requirements in #335, and our statsmodels requirements in #334, but we only updated  `requirements.txt` and `build_requirements.txt`, but forgot `doc_requirements.txt`. I don't think this affected the deploy of `1.6.1` -- the docs look correct, but I wanted to update it to keep everything in sync.
N/A
> [MRG+1] Bump our doc requirements as well

- pmdarima/arima/tests/test_arima.py
Related to #348, scipy 1.5.0 seems to have changed the internals of our function `AutoARIMA` class. No big deal, but our `to_dict` test is broken because we are comparing to hardcoded values generated using a previous release. It seems only `resid` and `bse` were really affected, from my digging. The short-term solution is to use `assert_allclose` with a high `rtol` for those tests
> [MRG+1] Fix to_dict test

- doc/whats_new.rst
- pmdarima/__init__.py
- pmdarima/arima/auto.py
- pmdarima/arima/tests/test_auto.py
- pmdarima/arima/tests/test_utils.py
- pmdarima/arima/utils.py
- pmdarima/compat/pytest.py
- pmdarima/context_managers.py
- pmdarima/tests/test_context_managers.py
Two recent issues pointed out areas where a large enough `m` could seasonally difference an array into being too small for fitting downstream models. This PR adds a custom error for #341 and a warning for #351 
Added new tests that capture the warning / custom error and assert on them.
> [MRG+1] Emit warnings / custom errors for differencing issues

- pmdarima/arima/tests/test_arima.py
- setup.cfg
I am unable to replicate @tgsmith61591's local experience:
`360 passed, 9673 warnings in 162.20s (0:02:42)`
But I was able to take my local (and CI) from this:
`360 passed, 1677 warnings in 129.89s (0:02:09)`
To this:
`360 passed in 110.10s (0:01:50)`
We were basically seeing 4 warnings:
- `DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
from collections import Mapping`
- This is [fixed in patsy](https://github.com/pydata/patsy/blob/4c613d0ad3009044ca3aee5a5d70bd56af8f396b/patsy/constraint.py#L13-L16), but I don't even know what is calling patsy, so we ignore it
- `DeprecationWarning: tostring() is deprecated. Use tobytes() instead.` (1672 of the warnings)
- This is fixed in …
> [MRG+1] Ignore warnings we don't care about in tests

- doc/contributing.rst
- doc/index.rst
- doc/no-successful-model.rst
- doc/user_guide.rst
- doc/whats_new.rst
- pmdarima/arima/_auto_solvers.py
- pmdarima/arima/arima.py
- pmdarima/arima/auto.py
- pmdarima/arima/tests/test_auto_solvers.py
Issue #354 pointed out a few corner cases where models with near non-invertable roots could still be considered as candidate models. This PR addresses those cases by filtering them from the returned stepwise search candidates.
Fixes #354
> [MRG] Address issue #354

- doc/whats_new.rst
- pmdarima/arima/arima.py
- pmdarima/arima/auto.py
- pmdarima/arima/tests/test_arima.py
Removes old (pre-1.2.0) behavior that split the statsmodels object out from the pmdarima object when serializing. This breaks backwards compatibility with old versions, but it was undesired, buggy behavior anyways. If a model was moved to another machine after serializing, it was un-loadable.
Tests of serialization have been updated, all other tests pass.
> [MRG+1] Remove legacy pickling behavior

- pmdarima/pipeline.py
- pmdarima/tests/test_pipeline.py
Currently, if there's an endogenous transformer in the pipeline and try to run `pipeline.predict(*, return_conf_int=True)`, pipeline would not do inverse transform. This pull request tries to fix this. 
Current tests cover this functionality.
> [MRG+2] support inverse_transformer when return_conf_int=True

- doc/migration-guide.rst
- doc/user_guide.rst
- pmdarima/arima/_validation.py
- pmdarima/arima/tests/test_validation.py
We still get issues asking about installing `pyramid-arima`, and despite the warning message the last version issues on install, people land here. I want to make the old doc link resolve to a migration guide rather than redirecting to the current home page.
> [DOC] Add a migration guide for pyramid -> pmdarima

- doc/whats_new.rst
- pmdarima/model_selection/_split.py
- pmdarima/model_selection/tests/test_split.py
Fixes the CV splits issue referenced in #364 
All existing tests pass, a new test has been added to assert on the number of CV folds created.
> [MRG+1] Fix cv splits

- build_tools/build_requirements.txt
- requirements.txt
This PR is a temporary fix with the release of statmodels 0.12 so our package will still work
> [MRG] Pin statsmodels to <0.12

- build_tools/build_requirements.txt
- requirements.txt
Setuptools released 50.0.0, which is breaking our build. This pins to setuptools < 50.0.0
> [HOTFIX] Pin setuptools

- .github/workflows/build_and_deploy.yml
- .github/workflows/test_tagging.yml
Remove push-to-branch trigger for GitHub Actions
> [MAINT] Do not run CI/CD on push to branch

- .circleci/config.yml
- .github/workflows/build_and_deploy.yml
- Makefile
- README.md
- build_tools/circle/build_manylinux_wheel.sh
- build_tools/circle/build_wheel.sh
- doc/index.rst
- doc/usecases/stocks.rst
- doc/usecases/sun-spots.rst
- doc/whats_new.rst
- setup.py
Python 3.5 is nearing its [end-of-life](https://endoflife.date/python). This PR removes all python 3.5 support, and cleans up various things in the `Makefile`
> [MRG+1] Remove python 3.5 support

- doc/index.rst
- doc/rfc/372-exog-to-x.rst
- doc/rfc/index.rst
This is an RFC proposing we switch the use of the `exogenous` arg to `X` for consistency with similar packages, and easy user onboarding. The reasons and approach are laid out in the `.rst` file in this PR.
Please leave comments, and reactions to this PR (👍  / 👎 ). I won't merge it for at least a week, and only if we decide to move forward with it.
(Inviting comments from some previous contributors @tuomijal @skyetim @mohitmunjal @christopher-siewert)
> [RFC] exogenous -> X

- .github/workflows/badges.yml
- .github/workflows/build_and_deploy.yml
- .github/workflows/test_tagging.yml
`setup-python@v1` uses a deprecated feature of github actions, so I am bumping to v2. Additionally, I am using 3.8 everywhere where we specify a version (`test tagging` and `update badges`)
> [MAINT+1] Use setup-python v2 everywhere

- pmdarima/model_selection/_split.py
- pmdarima/model_selection/tests/test_split.py
This PR fixes the upper bound in our `range` as called out in #364. Should unblock #369
> [MRG+1] Fix upper bound in RollingForecastCV

- build_tools/build_requirements.txt
- build_tools/circle/build_manylinux_wheel.sh
- requirements.txt
We pinned setuptools to `<50.0.0` in #379 due to the issue noted in https://github.com/pypa/setuptools/issues/2356. It seems to only affect v50.0.0, and we never forgot to unpin it. It is now causing issues (See #401). I think this should alleviate that.
> [MRG] Allow everything except setuptools 50.0.0

- build_tools/circle/deploy_doc.sh
- pmdarima/compat/statsmodels.py
- pmdarima/compat/tests/test_statsmodels.py
This PR addresses the compatibility check not allowing iterables in position 0 of the the seasonal_order tuple as pointed out in #370. It first assumes an iterable at position 0 (trying to be pythonic :)), and if it iterable we return unmodified. We only override the order in the special case of `(0,0,0,1)`. Additional changes were made to add test cases to check the special case of the override and the iterable not raising a `TypeError`.
Fixes #370 
- [`N/A`] I have made corresponding changes to the documentation
> [MRG+2] Add fix for issue#370 to allow iterables

- setup.py
The nightly build has been failing for macOS because numpy 1.2.0 (released 2021-01-30) deprecates some native libraries on macOS. This PR aims to address those concerns by following the numpy docs [here](https://numpy.org/devdocs/user/building.html#lapack)
> [MRG+1] Override env for mac builds

- .circleci/config.yml
- .github/workflows/build_and_deploy.yml
- .github/workflows/nightly_cron.yml
- build_tools/circle/build_wheel.sh
- doc/whats_new.rst
- setup.py
This PR adds Python 3.9 support. ~Still waiting on a few dependencies to support it, so this is a WIP for the time being~ ~There are still a few dependencies that don't have wheels published yet, but the ones we definitely don't want to build from scratch are out there, so this _technically_ works.~ All dependencies now support 3.9. It can sit in limbo if we'd rather have 100% support by dependencies first
Closes #389
> [MRG+1] Python 3.9 support

- build_tools/circle/build_wheel.sh
We had trouble deploying `1.8.1` for `3.8` and `3.9` because of this bad bash syntax. This should fix those deploys going forward (assuming we don't rewrite it first). Additionally, it updates our circle job to use a later version of the `manylinux` container to have Python 3.9 installed.
> [MRG+1] Fix bash syntax and update manylinux container

- .circleci/config.yml
- .github/workflows/build_and_deploy.yml
- build_tools/build_requirements.txt
- build_tools/circle/build_wheel.sh
- build_tools/circle/dind/build_manylinux_wheel.sh
- requirements.txt
This PR updates our `numpy` pin in two ways:
- It changes it in `requirements.txt` to be `numpy>=1.9.3` (undoing the `~=` pin and increasing the minimum version)
- The minimum version bump was because that was the first release that includes wheels for all the versions of Python we support
- It changes it in `build_tools/build_requirements.txt` to be `numpy~1.193`. The hope is we build on our minimum supported version and don't limit users in `requirements.txt`
It also updates CI/CD to use `build_tools/build_requirements.txt` where necessary and adds a regression check in GitHub Actions (@tgsmith61591 may need your help if you want a similar check in Circle)
Fixes #449 
If you look at #425, you'll remember we broke `sktime` last time we tried to do this. I believe that is because we built …
> [MRG] Change numpy pin to allow versions greater than 1.19.X

- doc/whats_new.rst
- pmdarima/arima/arima.py
- pmdarima/compat/sklearn.py
- pmdarima/pipeline.py
According to https://github.com/scikit-learn/scikit-learn/issues/20506 and https://github.com/scikit-learn/scikit-learn/issues/21144#issuecomment-926729714, it seems `if_delegate_has_method` is deprecated in favor of `available_if`. This is an attempt to switch to `available_if`
Fixes #454
> [MRG+1] Implement strategy from scikit-learn/scikit-learn#20506 

- pmdarima/compat/statsmodels.py
- pmdarima/utils/tests/test_wrapped.py
- pmdarima/utils/wrapped.py
This should fix the nightly build. The `unbiased` keyword and methods have been deprecated in `statsmodels` 0.13.0. A couple defaults for `acf` and `pacf` have also changed
> [MRG+1] Add compatibility for statsmodels 0.13 and higher

- CITATION.cff
- doc/whats_new.rst
This PR adds a `whats_new` entry for 1.8.4 that includes the statsmodels compatibility fix from #457, as well as updates the citation file to have a version of 1.8.4 and release date of 2021-11-05 (tomorrow)
N/A
N/A
> [MRG] Update whats_new and citation for 1.8.4

- .github/workflows/build_and_deploy.yml
- .github/workflows/nightly_cron.yml
This PR fixes a weird issue we are seeing with our mac builds. `macos-latest` seems to point to [`macos-11`](https://github.com/alkaline-ml/pmdarima/runs/4339908920?check_suite_focus=true#step:1:4) (despite what the [docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) say). However, when it builds a wheel, it builds for [macos-10.14](https://github.com/alkaline-ml/pmdarima/runs/4339908920?check_suite_focus=true#step:11:621) due to our Python version
```
[WARNING] This wheel needs a higher macOS version than the version your Python interpreter is compiled against.  To silence this warning, set MACOSX_DEPLOYMENT_TARGET to at least 11_0 or recreate these files with lower MACOSX_DEPLOYMENT_TARGET:
```
In the short term, we should just specify …
> [MRG+1] Switch to macos-10.15 instead of macos-latest

- .circleci/config.yml
- .github/workflows/build_and_deploy.yml
- README.md
- doc/whats_new.rst
- setup.py
Python 3.6 was [end-of-lifed on 2021-12-23](https://endoflife.date/python). This PR removes supports for Python 3.6.
Will need to change the "required checks" for this to pass. This will also conflict with #459, so I will have to update one depending one which is merged first 
N/A
> [MRG+1] Remove Python 3.6 support

- .circleci/config.yml
`circleci/classic` machines are being deprecated and removed ([blog post](https://circleci.com/blog/ubuntu-14-16-image-deprecation/)). This PR updates our Circle jobs that run on those VMs to run on `ubuntu-2004:202111-02` instead
I am hoping CI passes 🤞🏻
> [MRG] Don't use deprecated circlci/classic machines

- pmdarima/arima/_auto_solvers.py
- pmdarima/arima/_doc.py
- pmdarima/arima/auto.py
- pmdarima/arima/tests/test_auto.py
Please include a summary of the change and which issue is fixed:
When reading the docs I noticed that n_fits (which is used to determine the number of test iterations used to fit in random search cases) is sometimes referred to as n_iter. It looks like n_fits is the variable name that's actually in use. I looked for usages of n_iter and changed the ones which referred to n_fits. This is a very minor change which affects a few comments, one reference in documentation, and the text of a single error that's thrown if n_fits is negative. Please feel free to edit or reject.
Fixes # n/a
This is such a minor change (at first I thought it was doc-only) that I didn't file an issue first. Please let me know if I need to!
Please describe the tests that …
> [MRG+2] fix comments and doc which refer to n_fits as n_iter

- .github/workflows/build_and_deploy.yml
- .github/workflows/nightly_cron.yml
- .github/workflows/test_tagging.yml
- pmdarima/arima/seasonality.py
- pmdarima/model_selection/_split.py
- pmdarima/utils/tests/test_array.py
This PR makes it so if we push a commit to the same branch, it will cancel previous builds on GHA, saving us some cycles.
It also fixes a couple warnings in the build:
- `np.int` -> `int`
- `np.bool` -> `bool`
- `np.float` -> `float`
- `LinearRegression(normalize=True)` was apparently deprecated by sklearn in favor of `make_pipeline(StandardScaler(with_mean=False), LinearRegression())`
```
/Users/runner/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:
from sklearn.pipeline import make_pipeline
model = …
```
> [MRG+1] Add 'concurrency' block to GHA and fix build warnings

- .github/workflows/build_and_deploy.yml
- README.md
- doc/whats_new.rst
Windows is 1-2% of our user base ([source](https://pypistats.org/packages/pmdarima)) with 32-bit probably being a small fraction of that. Microsoft stopped offering 32-bit Windows in 2020, so there is no need to continue supporting it. We already stopped building 32-bit for 3.10+ due to dependencies not supporting it, v2.0 seems as good a time as ever to remove it completely. This should also help our build times since it reclaims 3 builds on each commit in GHA.
N/A
> [MRG+1] Sunset 32-bit builds

- doc/whats_new.rst
- pmdarima/arima/approx.py
- pmdarima/arima/arima.py
- pmdarima/arima/auto.py
- pmdarima/arima/seasonality.py
- pmdarima/arima/stationarity.py
- pmdarima/arima/tests/test_arima.py
- pmdarima/metrics.py
- pmdarima/model_selection/_validation.py
- pmdarima/pipeline.py
- pmdarima/preprocessing/base.py
- pmdarima/utils/array.py
- pmdarima/utils/tests/test_array.py
- pmdarima/utils/visualization.py
Permit users to produce in-sample predictions over indices that are non-integer, e.g. `model.predict_in_sample(start="20220103", end="20220106")`
Fixes #499 
- Add new tests for `check_endog` to assert we can preserve the index information
- Add two new ARIMA tests that show fitting over an index with a datetime dtype will allow users to predict either with an integer or date `start` value
> [MRG+1] Allow `predict_in_sample` for non-integer start/end indices

- .github/workflows/build_and_deploy.yml
- build_tools/circle/build_wheel.sh
Manylinux 2_24 is being EOLd, so we should use 2014 or 2_28. This PR standardizes on 2_28. See [this thread](https://github.com/pypa/manylinux/issues/1332#issuecomment-1148030224) for detail.
2_24 images can use a 2_28 wheel:
```
$ docker run -it -v $(pwd)/dist:/io quay.io/pypa/manylinux_2_24_x86_64 /bin/bash
root@ac32d12348a7:/# PYTHON=/opt/python/cp37-cp37m/bin/python
root@ac32d12348a7:/# PIP=/opt/python/cp37-cp37m/bin/pip
root@ac32d12348a7:/# $PIP install /io/pmdarima-0.0.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl 
Processing /io/pmdarima-0.0.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl
Collecting scipy>=1.3.2
Downloading scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB) …
```
> [MRG] Normalize on manylinux_2_28

- .circleci/config.yml
- .github/workflows/build_and_deploy.yml
- .github/workflows/nightly_cron.yml
- build_tools/build_requirements.txt
- doc/whats_new.rst
- requirements.txt
Cython version `0.29.31` broke our nightly build, so we want to avoid that (we have confirmed that the new `0.29.32` works). Separately macOS `10.15` is [deprecated by GitHub](https://github.com/actions/virtual-environments/issues/5583) so we bump to `macos-latest` (which is currently macOS `11`).
CI/CD passes
> [MRG] Update macOS version we build on and update Cython pin

- pmdarima/arima/arima.py
Changes:
- Printed `n_rows` and `n_periods` to screen in `ValueError` message. 
- Added spaces to other docstrings that were close together (automatically added by black formatter)
Motivation:
- I was using this method through the `sktime` package and kept getting this error. I was frustrated that neither `n_rows` or `n_periods` were printed to the screen as I was quite sure I was doing everything correctly. 
- [✅] Documentation change
No tests since it's just a doc change. Plus I had issues running pytest locally despite following your instructions.
- [✅] I have performed a self-review of my own code
- [✅] I have commented my code, particularly in hard-to-understand areas
- [✅] I have made corresponding changes to the documentation
- [✅] My changes generate no new warnings
- [NA] I have …
> [MRG+1] - Added extra info to ValueError in predict()

- pmdarima/pipeline.py
- pmdarima/preprocessing/endog/tests/test_boxcox.py
- pmdarima/preprocessing/exog/tests/test_fourier.py
This PR attempts to fix the `TypeError`s showing up in our [nightly builds](https://github.com/alkaline-ml/pmdarima/actions/runs/3655224217/jobs/6176356129). I can't explain why, but removing the keyword args is necessary to get anything that is a subtype of `_SetOutputMixin` to pass
> [MRG+1] Fix regression introduced by scikit-learn 1.2.0

- .github/workflows/build_and_deploy.yml
- pmdarima/arima/_auto_solvers.py
Our nightly build is [failing](https://github.com/alkaline-ml/pmdarima/actions/runs/3738252864/jobs/6344168234) due to [this expired deprecation](https://github.com/numpy/numpy/pull/22004). I think explicitly calling `dtype='object'` should fix it
> [MRG] Explicitly set dtype=object when generating permutations

- .circleci/config.yml
- .github/workflows/build_and_deploy.yml
- build_tools/build_requirements.txt
- pmdarima/compat/sklearn.py
- pmdarima/compat/statsmodels.py
- pmdarima/utils/wrapped.py
- requirements.txt
- setup.py
Remove `pkg_resources` because it is [deprecated](https://github.com/pypa/setuptools/pull/3843). Replace with what `pkg_resources.parse_version` calls [under the hood](https://github.com/pypa/setuptools/blob/b010f52705b41cd904813076447da3092776462a/pkg_resources/__init__.py#L134)
> [MRG] Remove pkg_resources

- .github/workflows/badges.yml
- .github/workflows/build_and_deploy.yml
- .github/workflows/nightly_cron.yml
- .github/workflows/test_tagging.yml
This PR:
- Fixes deprecations in our GitHub Actions workflows by changing `echo "::set-output name=foo::bar"` to `echo "foo=bar" >> $GITHUB_OUTPUT`
- Bumps our `setup-python` action to `v4`
- Bumps our `setup-qemu-action` to `v2`
- Changes `actions/checkout` to use a pinned version (`v3`) instead of `master`
- Updates our `badges` and `test_tagging` workflow to use python `3.11`
- As an aside, do we still need the `test_tagging` workflow?
- Bumps `cibuildwheel` to `2.11.2`
- Updates our `CITATION.cff` to the latest tag
- I think I am going to write a workflow that does this on a release. Seems like a cleaner option
> [MRG] Update CI/CD dependencies

- .github/workflows/nightly_cron.yml
- pmdarima/utils/_show_versions.py
Hopefully fixes the nightly build. Just took this implementation from [here](https://github.com/scikit-learn/scikit-learn/blob/b88b53985d9ddf8cec60414934c55a5745e8b958/sklearn/utils/_show_versions.py#L36-L71). Output still looks like this:
```
>>> import pmdarima
>>> pmdarima.show_versions()
System:
python: 3.10.6 (main, Sep 18 2022, 13:28:34) [Clang 13.1.6 (clang-1316.0.21.2.5)]
executable: /Users/asmith/.pyenv/versions/3.10.6/bin/python
machine: macOS-13.4.1-arm64-arm-64bit
Python dependencies:
setuptools: 63.2.0
pip: 23.0.1
sklearn: 1.2.0
statsmodels: 0.13.2
numpy: 1.23.3
scipy: 1.9.1
Cython: 0.29.32
pandas: 1.4.4
joblib: 1.2.0
pmdarima: 0.0.0
```
One difference is `seuptools` is before `pip` now in the output, due to [this](https://github.com/pypa/setuptools/issues/3044#issuecomment-10 …
> [MRG+1] Change how we implement show_versions()

- .github/workflows/build_and_deploy.yml
- build_tools/get_tag.py
Fixes our aarch builds so they deploy with the correct version
`GITHUB_REF` is now set for Linux builds ([example](https://github.com/alkaline-ml/pmdarima/actions/runs/6614883942/job/17965826278?pr=565#step:7:282))
> [MRG+1] Fix aarch builds

- .github/workflows/nightly_cron.yml
- pmdarima/arima/tests/test_validation.py
This PR fixes the nightly build by removing the use of `pytest.warns(None)` since it has been removed in pytest 8. It also bumps the Python version for nightly to 3.12
> [MRG] Fix nightly build

- pmdarima/arima/seasonality.py
Primary purpose here is to refactor the `CHTest()` class to add a new method `_calc_ch_crit_val()`. This brings it in-line with the `OCSBTest()` class, and will enable the user to extract the specific critical value used for the test.
The functionality does not change, all other processes remain the same.
While adding this change, I ran the `black` formatting on the `seasonality` module, which caused quite a few changes.
Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> [MRG+1] - Refactor seasonality module

- .github/workflows/build_and_deploy.yml
- build_tools/circle/build_wheel.sh
- setup.py
Sets `SETUPTOOLS_USE_DISTUTILS=stdlib` where necessary to get builds working again
> [MRG] Fix builds on Python < 3.12

- .circleci/config.yml
- .github/workflows/build_and_deploy.yml
- README.md
- build_tools/circle/build_wheel.sh
- doc/conf.py
- doc/sg_execution_times.rst
- doc/whats_new.rst
- pmdarima/arima/tests/test_arima_diagnostics.py
- pmdarima/datasets/tests/test_load_datasets.py
- setup.py
Python 3.7 is due to be [end-of-lifed on June 27, 2023](https://endoflife.date/python). This PR preps us to remove support for it.
Think this will depend on https://github.com/alkaline-ml/pmdarima-docker/pull/26
3.7 tests no longer exist, everything else still works
> [MRG+1] Remove support for Python 3.7
