pyramid/__init__.py, setup.py
This PR addresses minor inconsistencies that would have inhibited building the package and deploying it to pypi as a wheel.
This is necessary to address [issue#7](https://github.com/tgsmith61591/pyramid/issues/7).
=> Fix Setup.py for pypi

.travis.yml
- Added Travis CI integration for Slack.
=> Add slack integration to .travis.yml

.circleci/config.yml, .travis.yml, Makefile, build_tools/travis/after_success.sh, build_tools/travis/install.sh
This PR addresses #56 by moving over the coverage reporting tasks to Circle
=> [MRG] Migrate coverage

AUTHORS.md, doc/whats_new.rst, pmdarima/arima/arima.py, pmdarima/arima/auto.py, pmdarima/arima/tests/test_arima.py
#54 Added `to_dict` method to ARIMA class.
The tests gave me trouble. I wanted to test each key-value pair individually, but they all had to be treated slightly differently (hence the multiple asserts). If anyone has suggestions to clean that test up, please let me know.
=> [MRG+1] Added to_dict to ARIMA class

Makefile, README.md, build_tools/circle/build_test_pypy.sh, build_tools/travis/after_success.sh, doc/refreshing.rst, doc/whats_new.rst, examples/arima/example_add_new_samples.py, pmdarima/__init__.py, pmdarima/arima/arima.py, pmdarima/arima/auto.py, pmdarima/arima/tests/test_arima.py, pmdarima/decorators.py
This PR addresses issue #104 by adding a new method, `update`, to the ARIMA class.
The `add_new_observations` method was not working as expected for seasonal ARIMAs, and it appears the code for `update` in the statsmodels [SARIMAX](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/statespace/sarimax.py#L1456) class doesn't seem to work as expected. Even looking at the method, you can see the amount of work required to amend a simple internal variable... maintaining such behavior doesn't make sense for us, so I'm deprecating the old method in favor of `update`. Here's the gist:
* Where the old method attempted not to alter model parameters at all, the long-reaching spaghetti code of statsmodels meant there were way too many references we would have to update
* The new …
=> [MRG+1] Issue 104

pmdarima/preprocessing/endog/__init__.py, pmdarima/preprocessing/endog/fourier.py, pmdarima/preprocessing/endog/tests/test_boxcox.py, pmdarima/preprocessing/endog/tests/test_fourier.py
Part of #114 
* Added implementation for `FourierEndogTransformer`
* Added tests for above
Figured we would pull into `base-preprocess` so we can merge into `develop` when Pipeline is written
=> [MRG+1] Fourier transformation

build_tools/travis/after_wheel_build.sh
Commented out README check in `.travis.yml` so the deploy will not fail. Will need to address that later
=> [MRG+1] Fixed Travis build

pmdarima/arima/arima.py, pmdarima/arima/tests/test_arima.py
This PR adds confidence intervals for in-sample predictions, as requested in #125 
```python
>>> import pmdarima as pm
>>> y = pm.datasets.load_wineind()
>>> model = pm.ARIMA(order=(2, 0, 0)).fit(y)  # an ARMA model
>>> preds, confints = model.predict_in_sample(return_conf_int=True, alpha=0.05)
>>> preds
array([25398.48336295, 23487.73668294, 25376.12354149, 25806.0438565 ,
24693.34762964, 25186.47302587, 25395.55170427, 25981.45836902,
25493.56793698, 24763.48075805, 25564.26701577, 26220.7963937 ,
26100.27634328, 22313.79130298, 25670.21532598, 25575.43973705,
25498.53540268, 24841.79881527, 25762.31022239, 26092.91544304,
26066.68850131, 23798.20940319, 25521.80378351, 26416.3746824 ,
26033.9890663 , 22696.01439175, 25301.04292547, 25706.80578495,
25890.2284482 , 25077.79529332, …
```
=> [MRG+1] Confidence intervals for in-sample predictions

build_tools/circle/build_push_doc.sh, doc/contributing.rst, pmdarima/__init__.py
This should be the last piece required for #150 ... would appreciate eyes on other areas though to make sure I'm not wildly wrong.
=> [MRG] Adjust doc to only push on master and tags

.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
I was not aware we had a `feature request` tag, so this automatically adds that automatically when someone opens a feature request
N/A
=> [MRG+1] Added feature request tag

.circleci/config.yml, build_tools/circle/build_test_pypy.sh, doc/whats_new.rst, pmdarima/arima/arima.py, requirements.txt
This should fix #140 by exposing the `typ` keyword to the `predict_in_sample` method. Here's OP's example with the fix included (he actually had a minor bug in his example, but it's not a big deal):
```python
import pandas as pd
import pmdarima as pm
from matplotlib import pyplot as plt
X = pd.read_excel("/path/to/Downloads/array.xlsx")
array = X[X.columns[1]]
model_auto = pm.auto_arima(
array, start_p=0, start_q=0, max_p=10,
max_q=10, max_d=3, error_action="ignore",
seasonal=False, D=None, trace=True, stepwise=True,
enforce_stationarity=False, enforce_invertibility=False,
maxiter=5000)
preds = model_auto.predict_in_sample(array, typ='levels')
plt.plot(array, color='lightblue')
plt.plot(preds, color='blue')
from statsmodels.tsa.arima_model import ARIMA
model = ARIMA(array, …
```
=> [MRG+1] Fixes #140 (hopefully)

.circleci/config.yml
=> [MRG+1] Change environment variable sourcing in deploy

.github/stale.yml, .github/wip.yml
Added [WIP bot](https://github.com/wip/app) and [Stale bot](https://github.com/probot/stale)
N/A
=> [MRG+1] Configured our bots

doc/index.rst, pmdarima/__init__.py
Bumps version to 1.4.0 for upcoming release.
=> [MRG] Bump version to 1.4.0

pmdarima/model_selection/_split.py
Very simple doc fix for first issue. Thanks for making it easy to get involved :)
Fixes #204 
Only documentation change
Just to be sure I performed
`python setup.py develop`
`pytest`
241 Passed
=> [MRG+2] Fixed issue #204 [DOC] Misleading doc in SlidingWindowForecastCV

doc/tips_and_tricks.rst
Just closing a parenthesis.
- [x ] Documentation change
=> [MRG+1] Update tips_and_tricks.rst

doc/usecases/stocks.rst
Grammar correction, let me know if you want me to actually test this.
Just corrected the tense of one word in the documentation
=> [MRG] Update stocks.rst

AUTHORS.md, doc/modules/classes.rst, doc/tips_and_tricks.rst, pmdarima/arima/_auto_solvers.py, pmdarima/arima/_context.py, pmdarima/arima/auto.py, pmdarima/arima/tests/test_arima.py
Add Context Manager pattern to allow callers to set runtime context for calls into various functionalities. A new ```StepwiseContext``` content manager is added to enable passing of runtime configuration that offers additional level of control required in situations like, use cases that are either sensitive to duration and/or the number of attempts to find the best fit model. For example: building several hundreds (or even thousands) of models in a reasonable amount of time with a trade off between best fit model and amount of time.
Added unit tests to cover the new code and code paths and verified they pass the pytest.
=> [MRG+2] - add StepwiseContext feature

.github/workflows/badges.yml
Forgot to account for timezone in #223. The cron expression needs to be in UTC 
N/A
=> [MRG+1] Account for timezone

.github/workflows/badges.yml, etc/downloads_badges.py
Update GitHub action to install `requests` before it runs
N/A
=> [MRG+1] Fix badge action

doc/tips_and_tricks.rst, pmdarima/arima/_doc.py, pmdarima/arima/arima.py
Simply adds some documentation around performance gains and strategies, since that's become a common issue.
=> [MRG+1] Add some doc around performance boosts

.codecov.yml
This PR moves away from patch % on PRs for codecov validation and instead uses absolute coverage. See [here](https://docs.codecov.io/docs/commit-status#section-target).
Fixes [issue#232](https://github.com/tgsmith61591/pmdarima/issues/232).
=> [MRG+2] Absolute coverage

README.md, build_tools/circle/build_push_doc.sh, doc/_static/js/contrib.js
Post-organization migration fix for doc deployment
=> [MRG+2] Point to the proper repo

.circleci/config.yml, .gitignore, MANIFEST.in, build_tools/azure/build_and_deploy.yml, build_tools/azure/jobs.yml, build_tools/circle/install_from_sdist.sh, build_tools/get_tag.py, pmdarima/_build_utils/__init__.py, pmdarima/_build_utils/pre_build_helpers.py, pmdarima/setup.py, setup.py
=> [MRG+1] Fix sdist installation

build_tools/azure/build_and_deploy.yml, build_tools/azure/jobs.yml
Related to #249, this adds a similar sdist install check on Mac and Windows
=> [MRG+1] sdist install check on Windows and Mac

examples/seasonal_trend_decomposition_additive.ipynb, examples/seasonal_trend_decomposition_multiplicative.ipynb, pmdarima/arima/seasonality.py, pmdarima/arima/tests/test_seasonality.py
Fixes #254 by checking to make sure we reshape to an appropriate size and pad if necessary.
=> [MRG+1] Decompose Shape Fix

README.md
I updated the `installation` portion of the README in #248 and #263, but forgot to update the `availability` section 
N/A
N/A
=> [MRG+1] Fix README

build_tools/build_requirements.txt, doc/index.rst, doc/modules/classes.rst, doc/tips_and_tricks.rst, doc/usecases/stocks.rst, doc/whats_new.rst, pmdarima/arima/_auto_solvers.py, pmdarima/arima/_doc.py, pmdarima/arima/arima.py, pmdarima/arima/tests/test_arima.py, pmdarima/compat/sklearn.py, pmdarima/datasets/__init__.py, pmdarima/datasets/_base.py, pmdarima/datasets/gasoline.py, pmdarima/datasets/tests/test_load_datasets.py, pmdarima/preprocessing/base.py, requirements.txt
I added a new dataset: `US gasoline`. I also addressed #281 
Added new tests for web downloads of datasets, and a test of the fix for #281
=> [MRG+1] Update stock example & address #281

doc/whats_new.rst
One-line change to add `Conda fix` to the `whats_new` section of the Doc.
=> [MRG+1] Add to whats_new

doc/index.rst, doc/whats_new.rst
Update `whats_new.rst` to our new Cython and Statsmodels requirements
=> DOC: Update `whats_new`

doc/no-successful-model.rst, doc/whats_new.rst, pmdarima/arima/_auto_solvers.py, pmdarima/arima/_doc.py, pmdarima/arima/_validation.py, pmdarima/arima/arima.py, pmdarima/arima/auto.py, pmdarima/arima/tests/test_approx.py, pmdarima/arima/tests/test_arima.py, pmdarima/arima/tests/test_auto.py, pmdarima/arima/tests/test_auto_solvers.py, pmdarima/arima/tests/test_seasonality.py, pmdarima/arima/tests/test_validation.py, pmdarima/base.py, pmdarima/model_selection/tests/test_validation.py, pmdarima/preprocessing/exog/tests/test_fourier.py
Updating some logic in the stepwise algorithm to align with changes in `forecast` on master. Some highlights
* Improve tracing
* Add doc page with better explanation for why certain models may not be fit
* Change the default `with_intercept` from `True` to `"auto"`, which behaves truthy (maintaining existing behavior) but is explicitly set to True or False later in the algorithm given some differencing criteria
* General code refactoring
- Move `auto_arima` tests into their own file
- Keep `ARIMA` class tests in `test_arima`
- Add validation helpers to reduce logical branching
* The new intercept behavior seems to improve general performance significantly
* Lots of new tests
* All existing tests pass, with only one needing to be updated
=> [MAINT] Stepwise changes

doc/seasonal-differencing-issues.rst, doc/user_guide.rst, pmdarima/arima/seasonality.py, pmdarima/model_selection/_validation.py
Add a page with a more helpful explanation of why you might get the `There are no more samples after a first-order seasonal differencing` error
=> [DOC] Add a page

doc/whats_new.rst, pmdarima/arima/_validation.py, pmdarima/arima/arima.py, pmdarima/arima/tests/test_arima.py, pmdarima/arima/tests/test_validation.py
Addresses #368 by permitting custom scoring methods.
* Existing tests pass
* New test that uses a custom scoring metric in an ARIMA
* New test of various scoring metrics shows that expected errors are raised for invalid input
=> [MRG+1] Support custom scoring

build_tools/build_requirements.txt, doc/setup.rst, requirements.txt
This PR addresses these issues brought up in #376 by pinning statsmodels to `>=0.11,!=0.12.0`
=> [MRG+1] Change statsmodels pin

doc/whats_new.rst
Update `whats-new` for 1.8.0 release
N/A
N/A
=> [MRG] Update what's new for 1.8.0

doc/index.rst, doc/whats_new.rst, pmdarima/preprocessing/endog/log.py, pmdarima/preprocessing/endog/tests/test_log.py, pmdarima/tests/test_pipeline.py
Fixes #407
* Added a test for `clone`
* Added a test with `LogEndogTransformer` in a pipeline
=> [MRG+1] Fix LogEndogTransformer clone

build_tools/build_requirements.txt, build_tools/circle/install_from_sdist.sh, doc/whats_new.rst, requirements.txt
Fix our Cython pin so our users aren't stuck with an old version.
Addresses [this comment](https://github.com/alkaline-ml/pmdarima/issues/326#issuecomment-742423595)
Kinda just hoping CI/CD passes 🤞🏻
=> [MRG+1] Update Cython pin

examples/model_selection/example_cross_val_predict.py
Speeds up the CV example, which takes forever on Circle CI. Hopefully unblocks #413 
Example still runs, runs significantly faster
=> [MRG+1] Speed up the CV example

pmdarima/model_selection/_validation.py, pmdarima/model_selection/tests/test_validation.py
Implements functionality outlined in #364.
=> [MRG+1] Implement #364

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/question.yml, README.md, doc/setup.rst
This PR adds documentation for installing `pmdarima` via conda. Follow-on to #443 
N/A
=> [MRG] Add Conda install documentation and update issue templates

CITATION.cff, doc/whats_new.rst, pmdarima/compat/sklearn.py
This PR:
- bumps the citation version/release date
- Fixes some RST issues in `whats_new`
- Changes some double quotes to single quotes to be uniform
N/A
=> [MRG+1] Bump citation version and misc fixes

.circleci/config.yml, .github/workflows/build_and_deploy.yml, README.md, build_tools/build_requirements.txt, build_tools/circle/build_wheel.sh, doc/whats_new.rst, pmdarima/__init__.py, setup.py
This PR adds builds for Python 3.10, which was [released](https://www.python.org/downloads/release/python-3100/) on 2021-10-04. WIP because we will need to wait for dependencies to support 3.10
Hasn't yet 🤠
=> [MRG+1] Add builds for Python 3.10

README.md
Change minimum version in README
N/A
N/A
=> [MRG+1] Missed a 3.6 reference

CITATION.cff, build_tools/circle/build_wheel.sh, doc/index.rst
This PR:
- Bumps the citation version to 1.8.5 (released today)
- Removes an errant references to Python 3.6
- Adds a missing link in our documentation
N/A
N/A
=> [MRG] Bump citation version and date and misc. fixes

build_tools/build_requirements.txt, doc/index.rst, doc/whats_new.rst, pmdarima/arima/arima.py, pmdarima/arima/tests/test_arima.py, requirements.txt
Expose `fittedvalues` in the public `ARIMA` API
Fixes #(issue)
#493 
=> [MRG+1] Add `fittedvalues` to public ARIMA api

doc/whats_new.rst, pmdarima/arima/_doc.py, pmdarima/arima/arima.py
* Update `whats_new` doc for pre-2.0 release
* Turn one more old deprecation warning into an error
* Add explicit docstr for `seasonal_test_args` in `auto_arima` in response to #487 
=> [MRG+1] Update `whats_new`, doc

doc/about.rst
Fix typo superceded -> superseded in about doc 
=> [MRG+1] - Fix typo

doc/rfc/372-exog-to-x.rst, doc/usecases/sun-spots.rst, pmdarima/arima/auto.py, pmdarima/arima/seasonality.py
Signed-off-by: Ryan Russell <git@ryanrussell.org>
Improve readability and correct function references.
=> [MRG+1] Improve Readability

doc/quickstart.rst
Fixes the doc issue mentioned in #508 by (a) updating the output to something more modern and (b) adding a version disclaimer
N/A
=> [MRG+1] Update doc and add version footnote

doc/index.rst
Adds the 2.0.1 link to the doc home page.
N/A
N/A
=> [MRG] Add 2.0.1 link to doc index.rst

CITATION.cff, doc/whats_new.rst
Adds `whats_new` and updated citation for 2.0.3 release
N/A
=> [MRG] Update docs for 2.0.3

CITATION.cff
Update citation for new version
N/A
N/A
=> [MRG+1] Update citation

.github/workflows/build_and_deploy.yml, doc/whats_new.rst, requirements.txt
Pin numpy to `<2.0.0` to buy more time on #578 
Fixes #579
=> [MRG] Pin numpy to <2
